"""empty message

Revision ID: 131f6e0f4ffd
Revises: 
Create Date: 2020-10-11 10:20:01.386026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131f6e0f4ffd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrega_produtos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(length=120), nullable=True),
    sa.Column('delivery_content', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoque_produto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('img', sa.String(length=350), nullable=True),
    sa.Column('sku', sa.String(length=7), nullable=True),
    sa.Column('product_name', sa.String(length=100), nullable=True),
    sa.Column('amount_current', sa.Integer(), nullable=True),
    sa.Column('price_buy', sa.Float(), nullable=True),
    sa.Column('price_sell', sa.Float(), nullable=True),
    sa.Column('provider_supplies', sa.String(length=50), nullable=True),
    sa.Column('product_type', sa.String(length=50), nullable=True),
    sa.Column('amount_catia', sa.Integer(), nullable=True),
    sa.Column('amount_gerson', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estoque_produto')
    op.drop_table('entrega_produtos')
    # ### end Alembic commands ###
